Remove xib files where used UnderlinedTextField
VladYankovenko/TextFieldsCatalog pull request #1
Opened 2024-09-23 11:10 UTC by temurkhushvaktov

### Что сделано

- Удалил xib UnderlinedTextField и теперь верстка делается кодом
- [ ] UnderlinedTextView
- [ ] PickerTopView

### На что обратить внимание

- Проверить верстку в TextFieldsCatalogExample

2024-10-07 07:10 UTC, NullIsOne requested changes
Нашел парочку моментов над которыми можно подумать. 
Замечания к зашитым константам актуальны для всех изменений в верстке.

2024-10-07 07:10 UTC, NullIsOne commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +    /// Use when you don't need custom constraints
Надо бы подумать над передачей кастомных значений отступов сюда. 
Иногда могут возникнуть ситуации, когда дефолтные констрейнты в целом устраивают, но leading 16 это много или мало. 
Как в текущей конфигурации установить leading 32 например? 
Копипастить всю конфигурацию? Сложно.

Хотелось бы иметь более простой способ.
Например, сделать под `textField`, `hintLabel`, `actionButton` модельки с параметрами отступов и использовать эту модель в `configureDefaultLayout`
```
struct FieldConfiguration {
     let top: CGFloat
     let leading: CGFloat
     // ...
}
// аналогично для дефолтных hint + action

struct Configuration {
    let field: FieldConfiguration
    // ..
}
func configureDefaultLayout(with configuration: Configuration = .default) {
// ..
}
```

2024-10-07 07:10 UTC, NullIsOne commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +    public var textField = InnerTextField()
Можно ли оставить хотя бы `private(set)` ?
Открытие их в public чревато неоднозначной конфигурацией полей. 
Делегат поставят не там где надо или вообще заменят другим textField ..
Это все-таки библиотека. Надо предусмотреть варианты использования, чтобы результат был максимально предсказуемым.

2024-11-19 07:19 UTC, temurkhushvaktov commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +    public var textField = InnerTextField()
нет, так как это поле мы в других местах тоже настраиваем(BoxTextField к примеру). Если есть хорошее решение, давай обсудим

2024-11-19 08:30 UTC, NullIsOne commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +    /// Use when you don't need custom constraints
Вижу появилось layoutConfiguration
Хорошо подходит

2024-11-19 08:30 UTC, NullIsOne commented on TextFieldsCatalog/TextFields/UnderlinedTextField/UnderlinedTextField.swift
> +    public var textField = InnerTextField()
ок

2024-11-19 08:31 UTC, NullIsOne approved these changes

2025-02-11 09:11 UTC, merged